#!/bin/sh

UNAME=$(uname)
set -e
set -u

if [ "$UNAME" != "Linux" -a "$UNAME" != "Darwin" ] ; 
then
    echo "Your OS is not supported! This script works on Linux, MacOS or OS X"
    exit 1
fi

# Using 2.7 to support Arch Linux and other OS that use python 3 too.
PIPEXISTS=0
if [ -f /usr/bin/pip-2.7 ]; then PIPEXISTS=1; fi;
if [ -f /usr/local/bin/pip-2.7 ]; then PIPEXISTS=1; fi;

if [ $PIPEXISTS -eq 0 ]; then
    if [ -f  /usr/bin/apt-get ]; then

        read -p "A: python-pip not installed. Would you like to install via apt-get? [Y/n] " yn
        case $yn in
            [Yy]* ) sudo apt-get install beep python-pip python-dev;;
            '' ) sudo apt-get install beep python-pip python-dev;;
            * ) exit;;
        esac
        
    elif [ -f  /usr/bin/pacman ]; then
        read -p "A: python-pip not installed. Would you like to install via pacman? [Y/n] " yn
        case $yn in
            [Yy]* ) sudo pacman -S beep python2-pip;;
            '' ) sudo pacman -S beep python2-pip;;
            * ) exit;;
        esac    

    elif [ -f  /usr/bin/easy_install-2.7 ]; then
        read -p "A: python-pip not installed. Would you like to install via easy_install? [Y/n] " yn
        case $yn in
            [Yy]* ) sudo easy_install-2.7 pip;;
            '' ) sudo easy_install-2.7 pip;;
            * ) exit;;
        esac
    fi
fi

tmp_alread_installed="n"
if [ -f /usr/local/bin/steroids ]; then
    tmp_alread_installed="y"
fi

echo "Downloading and installing steroids... " 
sudo pip-2.7 install -U steroids -q
if [ -f /usr/bin/beep ]; then
    sudo beep -f 523.2 -l 138 -n -f 392.0 -l 138 -n -f 329.6 -l 138 -n -f 523.2 -l 138 -n -f 392.0 -l 138 -n -f 329.6 -l 138 -n -f 523.2 -l 828 -n -f 554.4 -l 138 -n -f 415.3 -l 138 -n -f 349.2 -l 138 -n -f 554.4 -l 138 -n -f 415.3 -l 138 -n -f 349.2 -l 138 -n -f 554.4 -l 828 -n -f 622.2 -l 138 -n -f 466.2 -l 138 -n -f 392.0 -l 138 -n -f 622.2 -l 138 -n -f 466.2 -l 138 -n -f 392.0 -l 138 -n -f 622.2 -l 414 -n -f 698.4 -l 138 -n -f 698.4 -l 138 -n -f 698.4 -l 138 -n -f 792 -l 1104
fi

if [[ "$tmp_alread_installed" == "y" ]]; then
    echo "Steroid upgraded correctly... #Daje! "
    exit 0;
fi

echo "Steroid installed correctly... #Daje! "
exit 0;
